package eu.sergiobelli.gebib.model.orm.data;

// Generated 13-nov-2007 10.57.48 by Hibernate Tools 3.2.0.b9

/**
 * Properties generated by hbm2java
 */
public class Properties implements java.io.Serializable {

	private String chiave;
	private String valore;

	public Properties() {
	}

	public Properties(String chiave, String valore) {
		this.chiave = chiave;
		this.valore = valore;
	}

	public String getChiave() {
		return chiave;
	}

	public void setChiave(String chiave) {
		this.chiave = chiave;
	}

	public String getValore() {
		return valore;
	}

	public void setValore(String valore) {
		this.valore = valore;
	}

}
