package eu.sergiobelli.gebib.model.orm.data;

// Generated 13-nov-2007 10.57.48 by Hibernate Tools 3.2.0.b9

/**
 * Publicazioni generated by hbm2java
 */
public class Publicazioni implements java.io.Serializable {

	private PublicazioniId id;

	public Publicazioni() {
	}

	public Publicazioni(PublicazioniId id) {
		this.id = id;
	}

	public PublicazioniId getId() {
		return this.id;
	}

	public void setId(PublicazioniId id) {
		this.id = id;
	}

}
