package eu.sergiobelli.gebib.model.orm.data;

// Generated 13-nov-2007 10.57.48 by Hibernate Tools 3.2.0.b9

/**
 * PublicazioniId generated by hbm2java
 */
public class PublicazioniId implements java.io.Serializable {

	private int idAutore;
	private int idLibro;

	public PublicazioniId() {
	}

	public PublicazioniId(int idAutore, int idLibro) {
		this.idAutore = idAutore;
		this.idLibro = idLibro;
	}

	public int getIdAutore() {
		return this.idAutore;
	}

	public void setIdAutore(int idAutore) {
		this.idAutore = idAutore;
	}

	public int getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(int idLibro) {
		this.idLibro = idLibro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicazioniId))
			return false;
		PublicazioniId castOther = (PublicazioniId) other;

		return (this.getIdAutore() == castOther.getIdAutore())
				&& (this.getIdLibro() == castOther.getIdLibro());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdAutore();
		result = 37 * result + this.getIdLibro();
		return result;
	}

}
